[project]
name = "medical-rag-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.65.4",
    "packaging>=24.2",
    "pydantic>=2.10.6",
    "pytest>=8.3.5",
    "streamlit>=1.43.0",
]
